# Generated by Django 4.2.16 on 2026-02-24 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('html_content', models.TextField(blank=True, default='')),
                ('pdf_file', models.FileField(blank=True, upload_to='proposals/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('extracted_proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_proposal', to='extraction.extractedproposal')),
            ],
        ),
    ]
