# Generated by Django 4.2.16 on 2026-02-24 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_extraction', models.JSONField(default=dict)),
                ('parties', models.JSONField(default=dict)),
                ('product', models.JSONField(default=dict)),
                ('pricing', models.JSONField(default=dict)),
                ('license_terms', models.JSONField(default=dict)),
                ('sla_terms', models.JSONField(default=dict)),
                ('special_conditions', models.JSONField(default=list)),
                ('ambiguities', models.JSONField(default=list)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('acceptance_signal', models.TextField(blank=True, default='')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_proposal', to='threads.emailthread')),
            ],
        ),
    ]
