"""Mock data simulating a Concertiv Outlook mailbox."""

VENDORS = ["Bloomberg LP", "Refinitiv", "FactSet"]
CLIENTS = ["Acme Capital", "Meridian Asset Management", "Zenith Capital Partners"]

VALID_PAIRS = {
    ("Bloomberg LP", "Acme Capital"): "thread_001",
    ("Refinitiv", "Meridian Asset Management"): "thread_002",
    ("FactSet", "Zenith Capital Partners"): "thread_003",
}

# ── Inbox emails (latest message from each thread + filler) ──────────────────

INBOX_EMAILS = [
    # Negotiation threads (latest message from each)
    {
        "id": "nego-001",
        "conversation_id": "thread_001",
        "subject": "Re: Bloomberg Terminal License Renewal - Acme Capital",
        "sender_name": "Sarah Chen",
        "sender_email": "sarah.chen@acmecapital.com",
        "to_name": "John Doe",
        "to_email": "john.doe@concertiv.com",
        "date": "2025-02-14T09:00:00Z",
        "preview": "That works for us. Please proceed with $20,500 per seat, 18 seats, 2-year term with a 3% year-two cap...",
        "is_read": True,
        "is_negotiation": True,
        "folder": "Inbox",
    },
    {
        "id": "nego-002",
        "conversation_id": "thread_002",
        "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management",
        "sender_name": "Priya Sharma",
        "sender_email": "priya.sharma@concertiv.com",
        "to_name": "David Park",
        "to_email": "david.park@meridianam.com",
        "date": "2025-02-13T11:00:00Z",
        "preview": "Great to see alignment from both sides. To confirm: $13,500 per seat, 25 seats, 2-year term...",
        "is_read": False,
        "is_negotiation": True,
        "folder": "Inbox",
    },
    {
        "id": "nego-003",
        "conversation_id": "thread_003",
        "subject": "Re: FactSet Terminal Access - Zenith Capital Partners",
        "sender_name": "Amanda Foster",
        "sender_email": "amanda.foster@factset.com",
        "to_name": "James Liu",
        "to_email": "james.liu@zenithcap.com",
        "date": "2025-02-24T09:45:00Z",
        "preview": "Absolutely — we can structure this as a flex arrangement. You'd start with 10 seats and have the option...",
        "is_read": False,
        "is_negotiation": True,
        "folder": "Inbox",
    },
    # Filler emails
    {
        "id": "filler-001",
        "conversation_id": "filler_conv_001",
        "subject": "Team Standup - Monday 9 AM",
        "sender_name": "HR Team",
        "sender_email": "hr@concertiv.com",
        "to_name": "All Staff",
        "to_email": "all-staff@concertiv.com",
        "date": "2025-02-25T08:00:00Z",
        "preview": "Reminder: Weekly standup meeting this Monday at 9 AM EST in Conference Room B. Please update your status...",
        "is_read": True,
        "is_negotiation": False,
        "folder": "Inbox",
    },
    {
        "id": "filler-002",
        "conversation_id": "filler_conv_002",
        "subject": "VPN Access Update - Action Required",
        "sender_name": "IT Support",
        "sender_email": "it-support@concertiv.com",
        "to_name": "All Staff",
        "to_email": "all-staff@concertiv.com",
        "date": "2025-02-24T11:00:00Z",
        "preview": "Please update your VPN client to version 4.2.1 before March 1st. The legacy version will be deprecated...",
        "is_read": True,
        "is_negotiation": False,
        "folder": "Inbox",
    },
    {
        "id": "filler-003",
        "conversation_id": "filler_conv_003",
        "subject": "Q4 2024 Financial Review - Final Report",
        "sender_name": "Robert Kim",
        "sender_email": "robert.kim@concertiv.com",
        "to_name": "Leadership Team",
        "to_email": "leadership@concertiv.com",
        "date": "2025-02-23T15:30:00Z",
        "preview": "Attached is the final Q4 2024 financial review. Revenue grew 12% YoY with strong performance in...",
        "is_read": True,
        "is_negotiation": False,
        "folder": "Inbox",
    },
    {
        "id": "filler-004",
        "conversation_id": "filler_conv_004",
        "subject": "Company All-Hands Meeting - February 28th",
        "sender_name": "CEO Office",
        "sender_email": "ceo-office@concertiv.com",
        "to_name": "All Staff",
        "to_email": "all-staff@concertiv.com",
        "date": "2025-02-22T10:00:00Z",
        "preview": "Please mark your calendars for our monthly all-hands on February 28th at 2 PM. Topics include Q1 goals...",
        "is_read": True,
        "is_negotiation": False,
        "folder": "Inbox",
    },
    {
        "id": "filler-005",
        "conversation_id": "filler_conv_005",
        "subject": "Welcome aboard, Emily!",
        "sender_name": "HR Team",
        "sender_email": "hr@concertiv.com",
        "to_name": "Client Services",
        "to_email": "client-services@concertiv.com",
        "date": "2025-02-21T09:00:00Z",
        "preview": "Please join us in welcoming Emily Rodriguez to the Client Services team. Emily joins us from JPMorgan...",
        "is_read": True,
        "is_negotiation": False,
        "folder": "Inbox",
    },
    {
        "id": "filler-006",
        "conversation_id": "filler_conv_006",
        "subject": "Expense Report Deadline - February 28",
        "sender_name": "Finance Team",
        "sender_email": "finance@concertiv.com",
        "to_name": "All Staff",
        "to_email": "all-staff@concertiv.com",
        "date": "2025-02-20T14:00:00Z",
        "preview": "Friendly reminder: all February expense reports must be submitted by EOD February 28th. Late submissions...",
        "is_read": True,
        "is_negotiation": False,
        "folder": "Inbox",
    },
    {
        "id": "filler-007",
        "conversation_id": "filler_conv_007",
        "subject": "Scheduled Server Maintenance - Feb 26, 10 PM",
        "sender_name": "IT Infrastructure",
        "sender_email": "it-infra@concertiv.com",
        "to_name": "All Staff",
        "to_email": "all-staff@concertiv.com",
        "date": "2025-02-19T16:30:00Z",
        "preview": "Our production servers will undergo scheduled maintenance on Feb 26 from 10 PM to 2 AM EST. Services may...",
        "is_read": True,
        "is_negotiation": False,
        "folder": "Inbox",
    },
    {
        "id": "filler-008",
        "conversation_id": "filler_conv_008",
        "subject": "Client Dinner - Goldman Sachs Team, March 5th",
        "sender_name": "Marcus Webb",
        "sender_email": "marcus.webb@concertiv.com",
        "to_name": "John Doe",
        "to_email": "john.doe@concertiv.com",
        "date": "2025-02-18T12:00:00Z",
        "preview": "Hi John, I've reserved a table at Del Posto for March 5th at 7 PM. The Goldman team confirmed 4 attendees...",
        "is_read": True,
        "is_negotiation": False,
        "folder": "Inbox",
    },
    {
        "id": "filler-009",
        "conversation_id": "filler_conv_009",
        "subject": "Office Holiday Hours - Presidents' Day",
        "sender_name": "Office Manager",
        "sender_email": "office@concertiv.com",
        "to_name": "All Staff",
        "to_email": "all-staff@concertiv.com",
        "date": "2025-02-14T10:00:00Z",
        "preview": "The office will be closed on Monday, February 17th for Presidents' Day. Regular hours resume Tuesday...",
        "is_read": True,
        "is_negotiation": False,
        "folder": "Inbox",
    },
    {
        "id": "filler-010",
        "conversation_id": "filler_conv_010",
        "subject": "Annual Compliance Training - Due March 15",
        "sender_name": "Compliance Dept",
        "sender_email": "compliance@concertiv.com",
        "to_name": "All Staff",
        "to_email": "all-staff@concertiv.com",
        "date": "2025-02-13T09:30:00Z",
        "preview": "Your annual compliance training modules are now available in the LMS. All employees must complete both...",
        "is_read": False,
        "is_negotiation": False,
        "folder": "Inbox",
    },
    {
        "id": "filler-011",
        "conversation_id": "filler_conv_011",
        "subject": "Concertiv Monthly Newsletter - February Edition",
        "sender_name": "Marketing Team",
        "sender_email": "marketing@concertiv.com",
        "to_name": "All Staff",
        "to_email": "all-staff@concertiv.com",
        "date": "2025-02-12T08:00:00Z",
        "preview": "This month: 3 new enterprise clients onboarded, our AI initiative update, team spotlight on the Data...",
        "is_read": True,
        "is_negotiation": False,
        "folder": "Inbox",
    },
    {
        "id": "filler-012",
        "conversation_id": "filler_conv_012",
        "subject": "Building Fire Drill - February 27, 2 PM",
        "sender_name": "Building Management",
        "sender_email": "building@management.com",
        "to_name": "All Tenants",
        "to_email": "tenants@building.com",
        "date": "2025-02-11T11:00:00Z",
        "preview": "A scheduled fire drill will take place on February 27th at 2 PM. All occupants must evacuate via...",
        "is_read": True,
        "is_negotiation": False,
        "folder": "Inbox",
    },
]

# Sort by date descending
INBOX_EMAILS.sort(key=lambda e: e["date"], reverse=True)

# ── Full thread data (same schema as ThreadIngestionService expects) ─────────

THREAD_DATA = {
    "thread_001": {
        "conversation_id": "thread_001",
        "subject": "Bloomberg Terminal License Renewal - Acme Capital",
        "participants": [
            {"name": "Sarah Chen", "email": "sarah.chen@acmecapital.com", "role": "client"},
            {"name": "Mike Torres", "email": "mike.torres@bloomberg.net", "role": "vendor"},
            {"name": "John Doe", "email": "john.doe@concertiv.com", "role": "concertiv"},
        ],
        "messages": [
            {"message_id": "msg-001", "from": {"name": "Sarah Chen", "email": "sarah.chen@acmecapital.com"}, "to": [{"name": "John Doe", "email": "john.doe@concertiv.com"}], "cc": [], "timestamp": "2025-02-10T09:15:00Z", "subject": "Bloomberg Terminal License Renewal - Acme Capital", "body": "Hi John,\n\nHope you're doing well. Our Bloomberg terminal licenses are coming up for renewal at the end of February and I wanted to get the process started. We currently have 18 seats at $22,000 per seat annually. We'd like to explore options for a renewal, ideally at a more competitive rate given our long-standing relationship with Bloomberg.\n\nCould you reach out to our Bloomberg contact and see what they can offer? We're open to a multi-year commitment if the pricing makes sense.\n\nThanks,\nSarah Chen\nHead of Operations\nAcme Capital"},
            {"message_id": "msg-002", "from": {"name": "John Doe", "email": "john.doe@concertiv.com"}, "to": [{"name": "Mike Torres", "email": "mike.torres@bloomberg.net"}], "cc": [{"name": "Sarah Chen", "email": "sarah.chen@acmecapital.com"}], "timestamp": "2025-02-10T14:30:00Z", "subject": "Re: Bloomberg Terminal License Renewal - Acme Capital", "body": "Hi Mike,\n\nI'm reaching out on behalf of our client Acme Capital regarding their Bloomberg terminal license renewal. They currently hold 18 seats at $22,000/seat and are looking to renew with improved pricing. They've been a Bloomberg client for over five years and would consider a multi-year commitment for the right terms.\n\nCould you put together a proposal for us?\n\nBest regards,\nJohn Doe\nClient Services Manager\nConcertiv"},
            {"message_id": "msg-003", "from": {"name": "Mike Torres", "email": "mike.torres@bloomberg.net"}, "to": [{"name": "John Doe", "email": "john.doe@concertiv.com"}], "cc": [{"name": "Sarah Chen", "email": "sarah.chen@acmecapital.com"}], "timestamp": "2025-02-11T10:45:00Z", "subject": "Re: Bloomberg Terminal License Renewal - Acme Capital", "body": "Hi John,\n\nThanks for reaching out. We value Acme Capital's loyalty and I'm happy to work on a competitive renewal package. Given their tenure and seat count, we can offer $21,500 per seat annually on a 2-year renewal commitment. This represents a meaningful discount from their current rate and locks in pricing stability.\n\nLet me know if Sarah would like to discuss further.\n\nBest,\nMike Torres\nEnterprise Account Executive\nBloomberg LP"},
            {"message_id": "msg-004", "from": {"name": "Sarah Chen", "email": "sarah.chen@acmecapital.com"}, "to": [{"name": "John Doe", "email": "john.doe@concertiv.com"}, {"name": "Mike Torres", "email": "mike.torres@bloomberg.net"}], "cc": [], "timestamp": "2025-02-12T08:20:00Z", "subject": "Re: Bloomberg Terminal License Renewal - Acme Capital", "body": "Hi Mike, John,\n\nAppreciate the offer. The $21,500 is a step in the right direction but not quite where we need to be. We've been benchmarking against comparable firms and believe $20,000 per seat is more in line with market rates for our volume. We'd also want a cap on year-two increases \u2014 no more than 3% \u2014 to ensure budget predictability.\n\nWould Bloomberg be open to those terms on a 2-year deal?\n\nThanks,\nSarah"},
            {"message_id": "msg-005", "from": {"name": "Mike Torres", "email": "mike.torres@bloomberg.net"}, "to": [{"name": "Sarah Chen", "email": "sarah.chen@acmecapital.com"}, {"name": "John Doe", "email": "john.doe@concertiv.com"}], "cc": [], "timestamp": "2025-02-13T11:00:00Z", "subject": "Re: Bloomberg Terminal License Renewal - Acme Capital", "body": "Hi Sarah,\n\nI appreciate the transparency on your benchmarking. After discussing with our pricing team, the best we can do is $20,500 per seat with a 3% annual cap on the year-two rate. We'd need a firm 2-year minimum commitment at 18 seats to hold this pricing. This is a significant concession from our standard renewal rates and reflects our investment in the long-term relationship.\n\nPlease let me know your thoughts.\n\nRegards,\nMike Torres\nEnterprise Account Executive\nBloomberg LP"},
            {"message_id": "msg-006", "from": {"name": "John Doe", "email": "john.doe@concertiv.com"}, "to": [{"name": "Sarah Chen", "email": "sarah.chen@acmecapital.com"}], "cc": [{"name": "Mike Torres", "email": "mike.torres@bloomberg.net"}], "timestamp": "2025-02-13T15:45:00Z", "subject": "Re: Bloomberg Terminal License Renewal - Acme Capital", "body": "Hi Sarah,\n\nJust wanted to summarize where we've landed with Bloomberg's latest offer so we can finalize:\n\n- Rate: $20,500 per seat per year\n- Seats: 18\n- Term: 2-year commitment\n- Year 2 escalation cap: 3%\n- Start date: March 1, 2025\n\nThis is a solid improvement over your current $22,000/seat rate. Could you confirm if these terms work for Acme Capital so we can move forward with the paperwork?\n\nBest,\nJohn Doe\nConcertiv"},
            {"message_id": "msg-007", "from": {"name": "Sarah Chen", "email": "sarah.chen@acmecapital.com"}, "to": [{"name": "John Doe", "email": "john.doe@concertiv.com"}, {"name": "Mike Torres", "email": "mike.torres@bloomberg.net"}], "cc": [], "timestamp": "2025-02-14T09:00:00Z", "subject": "Re: Bloomberg Terminal License Renewal - Acme Capital", "body": "Hi John, Mike,\n\nThat works for us. Please proceed with $20,500 per seat, 18 seats, 2-year term with a 3% year-two cap, effective March 1, 2025. We're happy with the outcome and appreciate the collaborative effort to get this done.\n\nLooking forward to the renewal documents.\n\nBest regards,\nSarah Chen\nHead of Operations\nAcme Capital"},
        ],
    },
    "thread_002": {
        "conversation_id": "thread_002",
        "subject": "Refinitiv Eikon Data Feed - Meridian Asset Management",
        "participants": [
            {"name": "David Park", "email": "david.park@meridianam.com", "role": "client"},
            {"name": "Lisa Wong", "email": "lisa.wong@meridianam.com", "role": "client"},
            {"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com", "role": "vendor"},
            {"name": "Tom Bailey", "email": "tom.bailey@refinitiv.com", "role": "vendor"},
            {"name": "Priya Sharma", "email": "priya.sharma@concertiv.com", "role": "concertiv"},
        ],
        "messages": [
            {"message_id": "msg-001", "from": {"name": "David Park", "email": "david.park@meridianam.com"}, "to": [{"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}], "cc": [], "timestamp": "2025-02-03T10:00:00Z", "subject": "Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi Priya,\n\nWe're evaluating market data providers and are interested in deploying Refinitiv Eikon across our research and trading teams. We'd need approximately 25 user licenses for the full data feed package. Can you reach out to Refinitiv and get us a quote? We're looking to have this in place by Q2.\n\nThanks,\nDavid Park\nCOO, Meridian Asset Management"},
            {"message_id": "msg-002", "from": {"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}, "to": [{"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}], "cc": [{"name": "David Park", "email": "david.park@meridianam.com"}], "timestamp": "2025-02-03T14:20:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi Rachel,\n\nI'm writing on behalf of Meridian Asset Management, who are looking to onboard Refinitiv Eikon for 25 users. They need the full data feed package including real-time and historical market data. Meridian is a mid-size asset manager with a strong growth trajectory, so this could be a valuable long-term partnership.\n\nCould you share enterprise pricing and available commitment options?\n\nBest,\nPriya Sharma\nVendor Relations\nConcertiv"},
            {"message_id": "msg-003", "from": {"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}, "to": [{"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}], "cc": [{"name": "David Park", "email": "david.park@meridianam.com"}], "timestamp": "2025-02-04T11:30:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi Priya,\n\nThank you for the introduction. For 25 users on the enterprise tier, our standard pricing is $15,000 per seat annually on a 3-year commitment. This includes real-time streaming data, historical data access, and our full analytics suite. We also offer onboarding and training support at no additional cost.\n\nHappy to schedule a demo if Meridian is interested.\n\nBest regards,\nRachel Adams\nSenior Sales Manager\nRefinitiv"},
            {"message_id": "msg-004", "from": {"name": "David Park", "email": "david.park@meridianam.com"}, "to": [{"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}, {"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}], "cc": [], "timestamp": "2025-02-05T09:15:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi Rachel, Priya,\n\nAppreciate the proposal. Candidly, $15,000 per seat is above our budget for this deployment. We've seen comparable offerings in the $12,000 range and would need to be closer to that figure to make this work. We're flexible on commitment length but the per-seat cost is the primary concern.\n\nCan you revisit the pricing?\n\nThanks,\nDavid"},
            {"message_id": "msg-005", "from": {"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}, "to": [{"name": "David Park", "email": "david.park@meridianam.com"}, {"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}], "cc": [], "timestamp": "2025-02-06T10:00:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi David,\n\nI understand budget constraints are a priority. After reviewing internally, we can offer $14,000 per seat with a 2-year commitment instead of the standard 3-year. This gives you more flexibility on term length while still providing a meaningful discount. The enterprise tier features remain unchanged.\n\nLet me know if this is closer to what works for Meridian.\n\nBest,\nRachel"},
            {"message_id": "msg-006", "from": {"name": "David Park", "email": "david.park@meridianam.com"}, "to": [{"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}, {"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}], "cc": [{"name": "Lisa Wong", "email": "lisa.wong@meridianam.com"}], "timestamp": "2025-02-07T08:45:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi all,\n\nWe're getting closer on pricing. Before we go further, I'm looping in Lisa Wong, our CTO, who has some questions around service-level guarantees and technical support. Lisa \u2014 Rachel and Priya have been working on Refinitiv Eikon pricing for our 25-user deployment. Can you weigh in on the SLA and support requirements?\n\nThanks,\nDavid"},
            {"message_id": "msg-007", "from": {"name": "Lisa Wong", "email": "lisa.wong@meridianam.com"}, "to": [{"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}], "cc": [{"name": "David Park", "email": "david.park@meridianam.com"}, {"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}], "timestamp": "2025-02-07T13:30:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi Rachel,\n\nThanks for the context, David. Rachel, our trading desk operates across US and European hours, so uptime is critical. What SLA commitments does Refinitiv offer on the Eikon platform? We'd also need clarity on support response times for P1 incidents and whether we'd have a dedicated technical contact.\n\nRegards,\nLisa Wong\nCTO, Meridian Asset Management"},
            {"message_id": "msg-008", "from": {"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}, "to": [{"name": "Lisa Wong", "email": "lisa.wong@meridianam.com"}], "cc": [{"name": "David Park", "email": "david.park@meridianam.com"}, {"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}, {"name": "Tom Bailey", "email": "tom.bailey@refinitiv.com"}], "timestamp": "2025-02-10T09:00:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi Lisa,\n\nGreat questions. I'm bringing in Tom Bailey from our technical services team to speak to the SLA specifics. Tom has deep experience with deployments similar to yours and can address your infrastructure and support requirements directly.\n\nTom, can you provide Lisa with details on our uptime commitments and premium support tiers?\n\nThanks,\nRachel"},
            {"message_id": "msg-009", "from": {"name": "Tom Bailey", "email": "tom.bailey@refinitiv.com"}, "to": [{"name": "Lisa Wong", "email": "lisa.wong@meridianam.com"}], "cc": [{"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}, {"name": "David Park", "email": "david.park@meridianam.com"}, {"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}], "timestamp": "2025-02-10T14:15:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi Lisa,\n\nFor the enterprise tier at 25 seats, we offer a 99.5% uptime SLA measured monthly across all data feed services. Our premium support tier includes 15-minute response times for P1 incidents during market hours and 1-hour response times for P2. You'd also have access to our 24/5 global support desk covering US and European trading sessions.\n\nHappy to walk through the technical architecture if helpful.\n\nBest,\nTom Bailey\nTechnical Services Director\nRefinitiv"},
            {"message_id": "msg-010", "from": {"name": "Lisa Wong", "email": "lisa.wong@meridianam.com"}, "to": [{"name": "Tom Bailey", "email": "tom.bailey@refinitiv.com"}], "cc": [{"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}, {"name": "David Park", "email": "david.park@meridianam.com"}, {"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}], "timestamp": "2025-02-11T10:30:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi Tom,\n\nThe support coverage sounds solid, but 99.5% uptime gives us roughly 3.6 hours of allowable downtime per month, which is a concern during peak trading. Is there any way to get to 99.9%? We've had issues with data outages at our current provider and reliability is a top priority for this switch.\n\nThanks,\nLisa"},
            {"message_id": "msg-011", "from": {"name": "Tom Bailey", "email": "tom.bailey@refinitiv.com"}, "to": [{"name": "Lisa Wong", "email": "lisa.wong@meridianam.com"}, {"name": "David Park", "email": "david.park@meridianam.com"}], "cc": [{"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}, {"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}], "timestamp": "2025-02-12T09:45:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi Lisa,\n\nI understand the concern. Unfortunately, 99.5% is the highest SLA we can contractually commit to for the Eikon platform at this tier. However, our actual measured uptime has been above 99.9% for the past 18 months. Additionally, we'd assign a dedicated account manager to Meridian to ensure priority handling of any service issues.\n\nBest,\nTom"},
            {"message_id": "msg-012", "from": {"name": "David Park", "email": "david.park@meridianam.com"}, "to": [{"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}, {"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}], "cc": [{"name": "Lisa Wong", "email": "lisa.wong@meridianam.com"}, {"name": "Tom Bailey", "email": "tom.bailey@refinitiv.com"}], "timestamp": "2025-02-13T08:30:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi Priya, Rachel,\n\nThanks everyone for working through the details. Lisa and I have discussed internally and we're comfortable with the 99.5% SLA given the actual uptime track record and the dedicated account manager. On pricing, we'd like to meet in the middle at $13,500 per seat for 25 seats on a 2-year commitment with premium support included.\n\nIf Refinitiv can confirm those terms, we're ready to move forward.\n\nBest,\nDavid Park\nCOO, Meridian Asset Management"},
            {"message_id": "msg-013", "from": {"name": "Priya Sharma", "email": "priya.sharma@concertiv.com"}, "to": [{"name": "David Park", "email": "david.park@meridianam.com"}, {"name": "Rachel Adams", "email": "rachel.adams@refinitiv.com"}], "cc": [{"name": "Lisa Wong", "email": "lisa.wong@meridianam.com"}, {"name": "Tom Bailey", "email": "tom.bailey@refinitiv.com"}], "timestamp": "2025-02-13T11:00:00Z", "subject": "Re: Refinitiv Eikon Data Feed - Meridian Asset Management", "body": "Hi David, Rachel,\n\nGreat to see alignment from both sides. To confirm what I'm hearing: $13,500 per seat, 25 seats, 2-year term, enterprise tier with premium support and 99.5% uptime SLA, plus a dedicated account manager. Rachel, if Refinitiv is good with this, let's get the paperwork started so we can target a Q2 deployment.\n\nThanks,\nPriya Sharma\nVendor Relations\nConcertiv"},
        ],
    },
    "thread_003": {
        "conversation_id": "thread_003",
        "subject": "FactSet Terminal Access - Zenith Capital Partners",
        "participants": [
            {"name": "James Liu", "email": "james.liu@zenithcap.com", "role": "client"},
            {"name": "Amanda Foster", "email": "amanda.foster@factset.com", "role": "vendor"},
            {"name": "Marcus Webb", "email": "marcus.webb@concertiv.com", "role": "concertiv"},
        ],
        "messages": [
            {"message_id": "msg-001", "from": {"name": "James Liu", "email": "james.liu@zenithcap.com"}, "to": [{"name": "Marcus Webb", "email": "marcus.webb@concertiv.com"}], "cc": [], "timestamp": "2025-02-10T08:30:00Z", "subject": "FactSet Terminal Access - Zenith Capital Partners", "body": "Hi Marcus,\n\nWe're exploring FactSet as our primary research and analytics platform. We'd need access for roughly 10 to 12 users depending on how our Q2 hiring goes. Can you get us a quote? We've used Bloomberg in the past but are looking at alternatives for cost reasons.\n\nThanks,\nJames Liu\nManaging Partner\nZenith Capital Partners"},
            {"message_id": "msg-002", "from": {"name": "Marcus Webb", "email": "marcus.webb@concertiv.com"}, "to": [{"name": "Amanda Foster", "email": "amanda.foster@factset.com"}], "cc": [{"name": "James Liu", "email": "james.liu@zenithcap.com"}], "timestamp": "2025-02-10T13:45:00Z", "subject": "Re: FactSet Terminal Access - Zenith Capital Partners", "body": "Hi Amanda,\n\nI'm reaching out on behalf of Zenith Capital Partners, who are evaluating FactSet for their research team. They're looking at 10-12 user licenses and are coming from a Bloomberg environment, so they'll need full terminal access including screening, analytics, and portfolio tools. Could you put together a proposal?\n\nBest,\nMarcus Webb\nClient Services\nConcertiv"},
            {"message_id": "msg-003", "from": {"name": "Amanda Foster", "email": "amanda.foster@factset.com"}, "to": [{"name": "Marcus Webb", "email": "marcus.webb@concertiv.com"}], "cc": [{"name": "James Liu", "email": "james.liu@zenithcap.com"}], "timestamp": "2025-02-11T10:00:00Z", "subject": "Re: FactSet Terminal Access - Zenith Capital Partners", "body": "Hi Marcus,\n\nThanks for the introduction. For Zenith Capital, we'd recommend our full workstation package at $18,000 per seat annually for 12 seats on a 3-year term. This includes our complete analytics suite, real-time data, screening tools, and portfolio analytics. Volume pricing kicks in at 12+ seats, which is why I'd recommend that tier.\n\nHappy to arrange a walkthrough for James and his team.\n\nBest regards,\nAmanda Foster\nAccount Executive\nFactSet"},
            {"message_id": "msg-004", "from": {"name": "James Liu", "email": "james.liu@zenithcap.com"}, "to": [{"name": "Marcus Webb", "email": "marcus.webb@concertiv.com"}, {"name": "Amanda Foster", "email": "amanda.foster@factset.com"}], "cc": [], "timestamp": "2025-02-12T09:20:00Z", "subject": "Re: FactSet Terminal Access - Zenith Capital Partners", "body": "Hi Amanda, Marcus,\n\nThanks for the proposal. The $18,000 per seat is higher than we were anticipating \u2014 our budget ceiling is around $15,000 per seat. Also, we may only need 10 seats initially rather than 12. We're still finalizing headcount for our new analyst class starting in Q2 so the exact number is a bit fluid. Is there flexibility on both price and the seat minimum?\n\nThanks,\nJames"},
            {"message_id": "msg-005", "from": {"name": "Amanda Foster", "email": "amanda.foster@factset.com"}, "to": [{"name": "James Liu", "email": "james.liu@zenithcap.com"}, {"name": "Marcus Webb", "email": "marcus.webb@concertiv.com"}], "cc": [], "timestamp": "2025-02-13T11:15:00Z", "subject": "Re: FactSet Terminal Access - Zenith Capital Partners", "body": "Hi James,\n\nI understand the budget considerations. We can offer $16,500 per seat with a minimum of 10 seats on a 2-year commitment. This removes the 3-year lock-in and gives you a lower entry point on seats. The full workstation feature set remains the same. Let me know if this is workable for your team.\n\nBest,\nAmanda"},
            {"message_id": "msg-006", "from": {"name": "James Liu", "email": "james.liu@zenithcap.com"}, "to": [{"name": "Marcus Webb", "email": "marcus.webb@concertiv.com"}], "cc": [{"name": "Amanda Foster", "email": "amanda.foster@factset.com"}], "timestamp": "2025-02-17T08:50:00Z", "subject": "Re: FactSet Terminal Access - Zenith Capital Partners", "body": "Hi Marcus,\n\nThanks for staying on top of this. The revised terms are closer to what we need, but I have to check with our team on the exact seat count before committing. We have a few hires in the pipeline that could push us to 12, but nothing confirmed yet. Let me circle back once I have more clarity \u2014 hopefully by end of next week.\n\nBest,\nJames"},
            {"message_id": "msg-007", "from": {"name": "Marcus Webb", "email": "marcus.webb@concertiv.com"}, "to": [{"name": "James Liu", "email": "james.liu@zenithcap.com"}], "cc": [{"name": "Amanda Foster", "email": "amanda.foster@factset.com"}], "timestamp": "2025-02-20T10:30:00Z", "subject": "Re: FactSet Terminal Access - Zenith Capital Partners", "body": "Hi James,\n\nJust following up \u2014 any update on the seat count from your team? Amanda's offer at $16,500 per seat with a 10-seat minimum is still on the table. Want to make sure we keep momentum on this so we can target an April deployment if you decide to move forward.\n\nBest,\nMarcus"},
            {"message_id": "msg-008", "from": {"name": "James Liu", "email": "james.liu@zenithcap.com"}, "to": [{"name": "Marcus Webb", "email": "marcus.webb@concertiv.com"}, {"name": "Amanda Foster", "email": "amanda.foster@factset.com"}], "cc": [], "timestamp": "2025-02-21T14:00:00Z", "subject": "Re: FactSet Terminal Access - Zenith Capital Partners", "body": "Hi Marcus, Amanda,\n\nSorry for the delay. We're thinking 10 to 12 seats \u2014 it really depends on how Q2 hiring shakes out. Our two senior analyst offers are out but not yet accepted. Realistically, can we start with 10 seats and add more later at the same per-seat rate if our headcount grows? That would give us the flexibility we need without overcommitting upfront.\n\nThanks,\nJames"},
            {"message_id": "msg-009", "from": {"name": "Amanda Foster", "email": "amanda.foster@factset.com"}, "to": [{"name": "James Liu", "email": "james.liu@zenithcap.com"}, {"name": "Marcus Webb", "email": "marcus.webb@concertiv.com"}], "cc": [], "timestamp": "2025-02-24T09:45:00Z", "subject": "Re: FactSet Terminal Access - Zenith Capital Partners", "body": "Hi James,\n\nAbsolutely \u2014 we can structure this as a flex arrangement. You'd start with 10 seats and have the option to add up to 5 additional seats during the contract term at the same per-seat rate. No penalty for staying at 10.\n\nLet me draft up an implementation timeline assuming 10 seats with an April 1 target go-live. We'd need about 3 weeks for provisioning, user setup, and training. I'll have our onboarding team put together a deployment plan and share it with Marcus by end of week.\n\nLooking forward to getting this moving.\n\nBest,\nAmanda Foster\nAccount Executive\nFactSet"},
        ],
    },
}
