# Generated by Django 4.2.16 on 2026-02-24 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField()),
                ('participants', models.JSONField(default=list)),
                ('raw_messages', models.JSONField(default=list)),
                ('flattened_thread', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipients', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField()),
                ('raw_body', models.TextField()),
                ('clean_body', models.TextField(blank=True, default='')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='threads.emailthread')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
